"""attrition-agent — an LLM-driven generation agent, not a template engine.

Reads daas/skills/*.md manifests + uses tools (write_file, edit_file,
ast_parse, run_shell, search_web, judge_with_rubric) to build scaffolds
for any of the 11 emit targets (simple_chain, tool_first_chain,
orchestrator_worker, openai_agents_sdk, langgraph_python,
claude_agent_sdk, deerflow, hermes, manus, convex_functions,
vercel_ai_sdk).

Driver runtime is swappable at session time:
    Gemini Agent (Google)
    OpenAI Agents SDK
    Anthropic Claude Agent SDK
    LangGraph (on top of any provider)
    OpenRouter (300+ models via one gateway)

Shape:  user's WorkflowSpec + chosen skill manifest
        --> AgentRuntime.run(system=<skill>, user=<spec>, tools=<our toolbox>)
        --> ArtifactBundle (same output shape as the f-string-templated
            emitters, but generated by the agent loop instead)

See docs/ATTRITION_AS_AGENT.md for the reasoning; see daas/skills/README.md
for how skills compose into the system prompt.
"""

from daas.agent.base import (
    AgentRunResult,
    AgentRuntime,
    Tool,
    ToolCall,
)
from daas.agent.tools import BUILD_TOOL_SET

__all__ = [
    "AgentRunResult",
    "AgentRuntime",
    "Tool",
    "ToolCall",
    "BUILD_TOOL_SET",
]
