"""Bundle finalizer — makes every emitted ZIP actually runnable.

After the lane-specific emitter returns its ArtifactBundle, this module
appends the connective tissue a user needs to clone-and-run:

    README.md         — what this is, how to run, how to flip connector mode
    requirements.txt  — pinned deps for the lane
    run.sh            — one-command entry point
    .env.example      — required API keys (copy to .env)

All four files are deterministic functions of (runtime_lane, spec), so
the same spec emits the same bundle on re-run. No network, no LLM.
"""

from __future__ import annotations

from typing import Any

from daas.compile_down.artifact import ArtifactBundle, ArtifactFile


# --- per-lane facts ------------------------------------------------------
_LANE_TITLE: dict[str, str] = {
    "simple_chain": "Simple chain — single LLM call with an output schema",
    "tool_first_chain": "Tool-first chain — bounded LLM + tool-call loop",
    "orchestrator_worker": "Orchestrator-worker — plan -> dispatch -> compact",
    "openai_agents_sdk": "OpenAI Agents SDK translation target",
    "langgraph_python": "LangGraph Python translation target",
}

_LANE_DEPS: dict[str, list[str]] = {
    "simple_chain": [
        "google-genai>=0.7.0",
    ],
    "tool_first_chain": [
        "google-genai>=0.7.0",
    ],
    "orchestrator_worker": [
        "google-genai>=0.7.0",
    ],
    "openai_agents_sdk": [
        "openai>=1.60.0",
        "openai-agents>=0.0.9 ; python_version>='3.10'",
    ],
    "langgraph_python": [
        "langgraph>=0.2.0",
        "langchain>=0.3.0",
        "langchain-google-genai>=2.0.0",
    ],
}

_LANE_ENV: dict[str, list[tuple[str, str]]] = {
    "simple_chain": [
        ("GEMINI_API_KEY", "Required — get one at https://aistudio.google.com/apikey"),
        ("CONNECTOR_MODE", "Optional — mock | live | hybrid (defaults to mock)"),
    ],
    "tool_first_chain": [
        ("GEMINI_API_KEY", "Required"),
        ("CONNECTOR_MODE", "Optional — mock | live | hybrid (defaults to mock)"),
        ("CONNECTOR_OVERRIDES", "Optional — JSON: {\"tool_name\": \"live\"} for per-tool overrides in hybrid mode"),
    ],
    "orchestrator_worker": [
        ("GEMINI_API_KEY", "Required — used by plan + per-worker + compact LLM calls"),
        ("CONNECTOR_MODE", "Optional — mock | live | hybrid"),
        ("CONNECTOR_OVERRIDES", "Optional — JSON overrides for hybrid"),
    ],
    "openai_agents_sdk": [
        ("OPENAI_API_KEY", "Required"),
        ("CONNECTOR_MODE", "Optional — mock | live | hybrid"),
    ],
    "langgraph_python": [
        ("GEMINI_API_KEY", "Required — graph LLM node uses Gemini by default"),
        ("CONNECTOR_MODE", "Optional — mock | live | hybrid"),
    ],
}

_LANE_ENTRYPOINT: dict[str, str] = {
    "simple_chain": "main.py",
    "tool_first_chain": "main.py",
    "orchestrator_worker": "orchestrator.py",
    "openai_agents_sdk": "main.py",
    "langgraph_python": "graph.py",
}


# --- file builders --------------------------------------------------------
def _readme(lane: str, spec: Any) -> str:
    title = _LANE_TITLE.get(lane, lane)
    entrypoint = _LANE_ENTRYPOINT.get(lane, "main.py")
    tools = _spec_tools(spec)
    tools_md = (
        "\n".join(f"- `{t}` — {_purpose_for(spec, t)}" for t in tools)
        if tools
        else "- (no tools declared in this spec)"
    )
    executor_model = getattr(spec, "executor_model", "gemini-3.1-flash-lite-preview")
    source_trace_id = getattr(spec, "source_trace_id", "")
    return f"""# {title}

Auto-generated by **attrition.sh** from trace `{source_trace_id}`.

Runtime lane: `{lane}`
Executor model: `{executor_model}`

## What this is

A runnable scaffold compiled down from a captured agent run. It was
distilled from the original trace into a canonical WorkflowSpec, then
emitted into this runtime lane. You can run it as-is in **mock** mode
to validate shape, or flip `CONNECTOR_MODE=live` once you've wired the
handlers in `tools.py` to real endpoints.

## Quick start

```bash
pip install -r requirements.txt
cp .env.example .env
# edit .env with your API key
./run.sh
```

Or directly:

```bash
python {entrypoint}
```

## Connector modes

This scaffold ships with two handlers per tool:
- `_stub_<name>(args)` — returns a mock response (fixture-placeholder)
- `_live_<name>(args)` — raises `NotImplementedError` until you wire it

Flip at runtime via env var:

```bash
CONNECTOR_MODE=mock   python {entrypoint}   # default
CONNECTOR_MODE=live   python {entrypoint}   # requires live handlers
CONNECTOR_MODE=hybrid CONNECTOR_OVERRIDES='{{"lookup_sku": "live"}}' python {entrypoint}
```

## Tools in this scaffold

{tools_md}

## How to wire a live handler

Open `tools.py` and replace the body of `_live_<tool_name>`:

```python
def _live_lookup_sku(args):
    # your real call here
    import requests
    r = requests.get("https://your.api/sku", params={{"id": args["id"]}})
    return r.json()
```

Then run with `CONNECTOR_MODE=live`.

## Regenerate from trace

```bash
# from the attrition repo
python -m daas.compile_down.cli \\
    --trace path/to/original.jsonl \\
    --lane {lane} \\
    --out ./regenerated
```

---

*Generated by attrition.sh · compile-down + verification layer.*
*Every `.py` in this bundle is `ast.parse`-valid on emit.*
"""


def _requirements(lane: str) -> str:
    deps = _LANE_DEPS.get(lane, ["google-genai>=0.7.0"])
    return "\n".join(deps) + "\n"


def _env_example(lane: str) -> str:
    rows = _LANE_ENV.get(lane, [("GEMINI_API_KEY", "Required")])
    lines: list[str] = [
        "# Environment for attrition-generated scaffold.",
        "# Copy this file to .env and fill in the required values.",
        "",
    ]
    for name, note in rows:
        lines.append(f"# {note}")
        lines.append(f"{name}=")
        lines.append("")
    return "\n".join(lines)


def _run_sh(lane: str) -> str:
    entrypoint = _LANE_ENTRYPOINT.get(lane, "main.py")
    return f"""#!/usr/bin/env bash
# One-command entry point for the attrition-generated scaffold.
set -euo pipefail

# Load .env if present (do not fail if missing — mock mode needs no key)
if [ -f .env ]; then
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a
fi

# Default to mock so first-run never crashes on missing live handlers.
export CONNECTOR_MODE="${{CONNECTOR_MODE:-mock}}"

# Use python3 on *nix, fall back to python on Windows.
if command -v python3 >/dev/null 2>&1; then
    PY=python3
else
    PY=python
fi

exec "$PY" {entrypoint} "$@"
"""


# --- spec helpers --------------------------------------------------------
def _spec_tools(spec: Any) -> list[str]:
    out: list[str] = []
    for t in getattr(spec, "tools", []) or []:
        if isinstance(t, dict):
            n = t.get("name")
        else:
            n = getattr(t, "name", None)
        if n:
            out.append(str(n))
    return out


def _purpose_for(spec: Any, tool_name: str) -> str:
    for t in getattr(spec, "tools", []) or []:
        if isinstance(t, dict):
            if t.get("name") == tool_name:
                return str(t.get("purpose", "")).strip() or "(no purpose declared)"
        else:
            if getattr(t, "name", None) == tool_name:
                p = str(getattr(t, "purpose", "") or "").strip()
                return p or "(no purpose declared)"
    return "(no purpose declared)"


# --- public entry --------------------------------------------------------
def finalize_bundle(
    bundle: ArtifactBundle,
    *,
    runtime_lane: str,
    spec: Any,
) -> ArtifactBundle:
    """Append README.md + requirements.txt + run.sh + .env.example to the
    bundle. Idempotent — skips files the emitter already produced.
    """
    existing_paths = {f.path for f in bundle.files}
    appended: list[ArtifactFile] = list(bundle.files)

    candidates: list[tuple[str, str, str]] = [
        ("README.md", _readme(runtime_lane, spec), "markdown"),
        ("requirements.txt", _requirements(runtime_lane), "text"),
        ("run.sh", _run_sh(runtime_lane), "shell"),
        (".env.example", _env_example(runtime_lane), "text"),
    ]
    for path, content, lang in candidates:
        if path in existing_paths:
            continue
        appended.append(ArtifactFile(path=path, content=content, language=lang))

    # Preserve the bundle's existing runtime_lane + target_model so we
    # don't lose metadata on finalize.
    kwargs: dict[str, Any] = {"files": appended}
    for name in ("runtime_lane", "target_model"):
        if hasattr(bundle, name):
            kwargs[name] = getattr(bundle, name)
    try:
        return ArtifactBundle(**kwargs)
    except TypeError:
        # Fall back to minimal construction if the dataclass signature
        # changes and doesn't accept our extras.
        return ArtifactBundle(files=appended)  # type: ignore[call-arg]
